version: "3"
services:
  
  ecommerce-app:
  
    build: ${ECOMMERCE_SERVICE_PATH}/Docker/app/.
    container_name: ${ECOMMERCE_SERVICE_NAME}
    command: ["npm", "run", "dev"]
  
    env_file:
      - ${ECOMMERCE_SERVICE_PATH}/Docker/app/.env
      - .env
    
    environment:
      - SEQUELIZE_HOST=${ECOMMERCE_MYSQL_NAME}
      - SEQUELIZE_DATABASE=${ECOMMERCE_MYSQL_DATABASE}
      - REDIS_HOST=${ECOMMERCE_REDIS_HOST}
      - FIRESTORE_EMULATOR_HOST=${ECOMMERCE_FIRESTORE_NAME}:8080
      - FIRESTORE_PROJECT_ID=${ECOMMERCE_FIRESTORE_NAME}

    volumes:
      - ${ECOMMERCE_SERVICE_PATH}/src:/app/src
      - ${ECOMMERCE_SERVICE_PATH}/tests:/app/tests
      - ${ECOMMERCE_SERVICE_PATH}/Docker/database/firestore-account:/app/firestore-account
      
    ports:
      - ${ECOMMERCE_APP_PORT}:8080
    
    depends_on:
      - ecommerce-mysql
      - ecommerce-redis
      - ecommerce-firestore
  
  ecommerce-mysql:
    
    platform: linux/x86_64
    build: ${ECOMMERCE_SERVICE_PATH}/Docker/database/.
    restart: always
    container_name: ${ECOMMERCE_MYSQL_NAME}
  
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${ECOMMERCE_MYSQL_DATABASE}

    ports:
      - ${ECOMMERCE_MYSQL_PORT}:3306
  
    command: 
      - --default-authentication-plugin=mysql_native_password

  ecommerce-redis:
  
    container_name: ${ECOMMERCE_REDIS_HOST}
    image: redis:alpine
  
  ecommerce-firestore:

    container_name: ${ECOMMERCE_FIRESTORE_NAME}
    image: mtlynch/firestore-emulator

    environment:
      FIRESTORE_PROJECT_ID: ${ECOMMERCE_FIRESTORE_NAME}
