### Obtener todas las categorias.
GET http://localhost:8001/categories

### Obtener categoria por ID.
GET http://localhost:8001/categories/1

### Crear categoria.
POST http://localhost:8001/categories
Content-Type: application/json

{
    "name": "Categoría 1",
    "description": "Descripción"
}

### Actualizar categoria.
PUT http://localhost:8001/categories/gIIQnRJzmonQ4WgUqEZq
Content-Type: application/json

{
  "name": "Nueva categoría 1",
  "description": "Nueva descripción"
}

### Borrar categoria.
DELETE http://localhost:8001/categories/gIIQnRJzmonQ4WgUqEZq


### Obtener todos los usuarios.
GET http://localhost:8001/users

### Obtener usuario por ID.
GET http://localhost:8001/users/1

### Crear usuario.
POST http://localhost:8001/users
Content-Type: application/json

{
  "name": "Comprador 2",
  "email": "admin2@gmail.com",
  "password": "123456",
  "is_admin": false
}

### Actualizar usuario.
PUT http://localhost:8001/users/1
Content-Type: application/json

{
  "name": "User",
  "email": "user@gmail.com",
  "password": "password",
  "is_admin": false
}

### Borrar usuario.
DELETE http://localhost:8001/users/gIIQnRJzmonQ4WgUqEZq


### Obtener todos los productos.
GET http://localhost:8001/products

### Obtener producto por ID.
GET http://localhost:8001/products/1

### Crear producto.
POST http://localhost:8001/products
Content-Type: application/json

{
  "name": "Producto 10",
  "description": "descripción producto",
  "quantity": 5,
  "SellerUserId": 3,
  "CategoryId": 2
}

### Actualizar producto.
PUT http://localhost:8001/products/1
Content-Type: application/json

{
  "name": "Nuevo producto 1",
  "description": "Nueva descripción producto 1",
  "quantity": 4,
  "SellerUserId": 3,
  "CategoryId": 2
}

### Borrar producto.
DELETE http://localhost:8001/products/gIIQnRJzmonQ4WgUqEZq


### Obtener todas las transacciones.
GET http://localhost:8001/transactions

### Obtener transaccion por ID.
GET http://localhost:8001/transactions/1

### Crear transaccion.
POST http://localhost:8001/transactions
Content-Type: application/json

{
  "BuyerUserId": 5,
  "ProductIds": [
    1,
    2,
    3
  ]
}

### Actualizar transaccion.
PUT http://localhost:8001/transactions/1
Content-Type: application/json

{
  "name": "Nuevo transaccion 1",
  "description": "Nueva descripción transaccion 1",
  "quantity": 0
}

### Borrar transaccion.
DELETE http://localhost:8001/transactions/7
