### Obtener todas las categorias.
GET http://localhost:8001/categories

### Obtener categoria por ID.
GET http://localhost:8001/categories/1

### Crear categoria.
POST http://localhost:8001/categories
Content-Type: application/json

{
    "name": "Categoría 1",
    "description": "Descripción"
}

### Actualizar categoria.
PUT http://localhost:8001/categories/gIIQnRJzmonQ4WgUqEZq
Content-Type: application/json

{
  "name": "Nueva categoría 1",
  "description": "Nueva descripción"
}

### Borrar categoria.
DELETE http://localhost:8001/categories/gIIQnRJzmonQ4WgUqEZq


### Obtener todas los usuarios.
GET http://localhost:8001/users

### Obtener usuario por ID.
GET http://localhost:8001/users/1

### Crear usuario.
POST http://localhost:8001/users
Content-Type: application/json

{
  "name": "Admin 2",
  "email": "admin2@gmail.com",
  "password": "123456",
  "is_admin": true
}

### Actualizar usuario.
PUT http://localhost:8001/users/1
Content-Type: application/json

{
  "name": "User",
  "email": "user@gmail.com",
  "password": "password",
  "is_admin": false
}

### Borrar usuario.
DELETE http://localhost:8001/users/gIIQnRJzmonQ4WgUqEZq
